//@host = https://falling-bush-8725.fly.dev/api/persons
@host = http://localhost:3001/api/persons

POST {{host}} HTTP/1.1
content-type: application/json

{
    "number": "555-123456"
}

###

POST {{host}} HTTP/1.1
content-type: application/json

{
    "name": "",
    "number": "555-123456"
}

###


POST {{host}} HTTP/1.1
content-type: application/json

{
    "name": "Sirpa K."
}

###

POST {{host}} HTTP/1.1
content-type: application/json

{
    "name": "Sirpa K.",
    "number": ""
}

###

POST {{host}} HTTP/1.1
content-type: application/json

{
    "name": "Sirpa K.",
    "number": "555-123456"
}

###

POST {{host}} HTTP/1.1
content-type: application/json

{
    "name": "J. Käyhkö",
    "number": "040-1237658"
}

###

POST {{host}} HTTP/1.1
content-type: application/json

{
    "name": "Pertti Mäyrä",
    "number": "050-532666"
}
